# Generated by Django 6.0.6 on 2026-07-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_booking_payment_method_booking_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='owner_profiles/'),
        ),
    ]
