# Generated by Django 6.0.6 on 2026-07-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_owner_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='renter_profiles/'),
        ),
    ]
